version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo_app
    container_name: todo_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todo
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"  

  db:
    image: mysql:8.0
    container_name: todo_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3308:3306"  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
